### ISSUE TITLE
Recent release broke our build

### ISSUE THREAD

**Issue by stbrody** [multiformats/js-multibase#90]
**Describe the bug**
All of a sudden today the build in our CI system started failing with the error:
```
 FAIL  src/__tests__/doc-id.test.ts
  ● Test suite failed to run

    ReferenceError: TextDecoder is not defined

    > 1 | import CID from 'cids';
        | ^
      2 | import multibase from 'multibase';
      3 | import * as doctypes from './doctypes';
      4 | import varint from 'varint';

      at Object.<anonymous> (node_modules/multibase/src/util.js:3:21)
      at Object.<anonymous> (node_modules/multibase/src/base.js:3:24)
      at Object.<anonymous> (node_modules/multibase/src/constants.js:4:14)
      at Object.<anonymous> (node_modules/multibase/src/index.js:7:19)
      at Object.<anonymous> (node_modules/cids/node_modules/multihashes/src/index.js:6:19)
      at Object.<anonymous> (node_modules/cids/src/index.js:3:12)
      at Object.<anonymous> (src/doc-id.ts:1:1)
      at Object.<anonymous> (src/__tests__/doc-id.test.ts:1:1)
```

Note that I didn't manually update package.json in any way to get to the newest version, we just use the `^` and `~` in some places to pull in newer minor versions of packages when they get released, but minor versions aren't supposed to include breaking changes.  It seems like when multibase v4.0.3 got released, npm picked it up and started using it in CI, which broke our build. Note our package.json specifies `"multibase": "~4.0.2"`.

I'm currently in the process of going through all our package.json files and pinning to version 4.0.2 to get things working again, but ideally this wouldn't be necessary as the semantic versioning system should already protect us against pulling in unexpected breaking changes.

**Desktop (please complete the following information):**
 - OS: uname -a: `Linux Sonny 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**

**Comment by stbrody** [comment]
Note this is likely related to https://github.com/achingbrain/uint8arrays/issues/17 as they started happening at the same time and look very similar

**Comment by stbrody** [comment]
We were able to fix this by setting `--env=node` in our jest configuration.  Closing as there's no actual issue in `multibase`
